# https://taskfile.dev

version: '3'

tasks:

  init:
    cmds:
      - cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    aliases:
      - i

  build:
    dir: "./build"
    cmds:
      - cmake ..
      - make
    aliases:
      - b
  
  clean:
    cmds:
      - rm -rf build

  run:
    cmds:
      - task: build
      - ./build/aoc
    aliases:
      - r

  format:
    cmds:
      - clang-format -i --style=file $(find advent24/ -name '*.cc' -o -name '*.hpp')
      - clang-format -i --style=file $(find junelib/ -name '*.cc' -o -name '*.hpp')
    aliases:
      - f

  precommit:
    cmds:
      - task: lint
      - task: format
