name: "[ci] Run clint on src files"

on:
  push:
    paths:
      - '**'
  pull_request:
    paths:
      - '**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM 20
        run: |
            wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
            sudo apt-add-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main"
            sudo apt update
            sudo apt install llvm-20 llvm-20-dev llvm-20-tools clang-20 clang-tidy-20 clang-format-20 clang-tools-20 libclang-20-dev -y
            sudo apt install libc++-20-dev libc++abi-20-dev -y

      - name: Configure CMake
        run: |
            cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        env:
          CC: clang-20
          CXX: clang++-20

      - name: Run clang-tidy
        run: |
            find src/ -name '*.cc' | xargs clang-tidy-20 -p build

      - name: Run clang-format
        run: |
            clang-format-20 --dry-run --Werror --style=file $(find src/ -name '*.cc' -o -name '*.h')

      - name: Build and run
        run: |
            cd build
            make
            cd ..
            ./build/aoc
